version 0.4.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Anticonf (tm) script by Jeroen Ooms (2018)
 # This script will query 'pkg-config' for the required cflags and ldflags.
 # If pkg-config is unavailable or does not find the library, try setting
@@ -13,6 +13,19 @@ PKG_CSW_NAME="ffmpeg_dev"
 PKG_BREW_NAME="ffmpeg"
 PKG_TEST_HEADER="<libavfilter/version.h>"
 PKG_LIBS="-lavfilter"
+
+# Check if FFmpeg is too old
+pkg-config ${PKG_CONFIG_NAME} --max-version=5.99 2>/dev/null
+if [ $? -eq 0 ]; then
+  echo "ERROR: Your version of FFmpeg is too old! Need at least FFmpeg (>= 3.2)" 1>&2
+  if [ "$(lsb_release -c 2>/dev/null | grep xenial)" ]; then
+    echo "On Ubuntu Trusty/Xenial use our PPA: " 2>/dev/null
+    echo "  sudo add-apt-repository -y ppa:cran/ffmpeg-3" 2>/dev/null
+    echo "  sudo apt-get update" 2>/dev/null
+    echo "  sudo apt-get dist-upgrade" 2>/dev/null
+  fi
+  exit 1
+fi
 
 # FFMPEG 3 and 4 include libavfilter 6.0
 pkg-config ${PKG_CONFIG_NAME} --atleast-version=6 2>/dev/null
@@ -46,12 +59,12 @@ echo "Using PKG_CFLAGS=$PKG_CFLAGS"
 echo "Using PKG_LIBS=$PKG_LIBS"
 
 # Find compiler
-CXXCPP=$(${R_HOME}/bin/R CMD config CXXCPP)
+CXX=$(${R_HOME}/bin/R CMD config CXX)
 CXXFLAGS=$(${R_HOME}/bin/R CMD config CXXFLAGS)
 CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
 
 # Test for libzmq
-echo "#include $PKG_TEST_HEADER" | ${CXXCPP} ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ -  >/dev/null 2>&1
+echo "#include $PKG_TEST_HEADER" | ${CXX} -E ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ -  >/dev/null 2>&1
 
 if [ $? -ne 0 ]; then
   echo "------------------------- ANTICONF ERROR ---------------------------"
